project:
  type: book
  output-dir: docs

book:
  title: "Advanced Cognitive Modeling Notes"
  author: "Riccardo Fusaroli"
  date: today
  repo-url: https://github.com/fusaroli/AdvancedCognitiveModeling2023
  repo-branch: main
  repo-actions: [edit]
  chapters:
    - index.qmd
    - 01-PizzaExperiment.qmd
    - 02-BuildingModels.qmd
    - 03-BuildingFormalModels.qmd
    - 04-InferringRates.qmd
    - 05-ModelQualityChecks.qmd
    - 06-MultilevelModels.qmd
    - 07-ModelComparison.qmd
    - 08-MixtureModels.qmd
    - 09-TheoryOfMind.qmd
    - 10-BayesianModels.qmd
    - 11-CategorizationModelsExemplars.qmd
  appendices:
    - 10a-BayesianSequentialExtensions.qmd

bibliography:
  - book.bib
  - packages.bib

format:
  html:
    theme: cosmo
    toc: true
    search: true
    page-navigation: true
  pdf: default
